spring.application.name=backend

# Habilita la lectura del archivo .env 
spring.config.import=optional:file:.env[.properties]

# Configuraci\u00f3n del Driver y las credenciales din\u00e1micas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuraci\u00f3n de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto del servidor y Swagger
server.port=8080
springdoc.swagger-ui.path=/docs